package com.vinithius.dex10.scanner

import android.content.Context
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import okhttp3.Request
import java.io.File
import java.io.IOException
import java.util.concurrent.TimeUnit

/**
 * Downloads and stores the on-device Pokémon recognition model (INT8 ONNX, ~85 MB).
 *
 * The model is not bundled in the APK to keep the install size small; it is fetched
 * once from a GitHub release asset and kept in internal storage.
 */
class ScannerModelManager(private val context: Context) {

    sealed class ModelState {
        object NotDownloaded : ModelState()
        data class Downloading(val progress: Float) : ModelState()
        data class Ready(val file: File) : ModelState()
        data class Error(val message: String?) : ModelState()
    }

    private val modelDir: File
        get() = File(context.filesDir, "scanner").apply { mkdirs() }

    private val modelFile: File
        get() = File(modelDir, MODEL_FILE_NAME)

    private val client = OkHttpClient.Builder()
        .connectTimeout(30, TimeUnit.SECONDS)
        .readTimeout(120, TimeUnit.SECONDS)
        .build()

    private val _state = MutableStateFlow(initialState())
    val state: StateFlow<ModelState> = _state

    private fun initialState(): ModelState =
        if (modelFile.length() >= MIN_VALID_BYTES) ModelState.Ready(modelFile) else ModelState.NotDownloaded

    suspend fun download() = withContext(Dispatchers.IO) {
        if (modelFile.length() >= MIN_VALID_BYTES) {
            _state.value = ModelState.Ready(modelFile)
            return@withContext
        }
        if (_state.value is ModelState.Downloading) return@withContext
        _state.value = ModelState.Downloading(0f)
        val tmpFile = File(modelDir, "$MODEL_FILE_NAME.tmp")
        try {
            client.newCall(Request.Builder().url(MODEL_URL).build()).execute().use { response ->
                if (!response.isSuccessful) throw IOException("HTTP ${response.code}")
                val body = response.body ?: throw IOException("Empty body")
                val totalBytes = body.contentLength()
                body.byteStream().use { input ->
                    tmpFile.outputStream().use { output ->
                        val buffer = ByteArray(DEFAULT_BUFFER_SIZE)
                        var downloaded = 0L
                        while (true) {
                            val read = input.read(buffer)
                            if (read < 0) break
                            output.write(buffer, 0, read)
                            downloaded += read
                            if (totalBytes > 0) {
                                _state.value = ModelState.Downloading(downloaded.toFloat() / totalBytes)
                            }
                        }
                    }
                }
            }
            if (tmpFile.length() < MIN_VALID_BYTES) throw IOException("Incomplete download")
            modelFile.delete()
            if (!tmpFile.renameTo(modelFile)) throw IOException("Could not persist model file")
            _state.value = ModelState.Ready(modelFile)
        } catch (e: Exception) {
            tmpFile.delete()
            _state.value = ModelState.Error(e.message)
        }
    }

    companion object {
        // INT8-quantized ViT classifier (Gen 1-9, 1025 classes), generated by
        // ml/convert_pokemon_classifier.py and published as a GitHub release asset.
        const val MODEL_URL =
            "https://github.com/vinithius2/Dex10-Pokedex/releases/download/scanner-model-v1/pokemon_classifier_int8.onnx"
        const val MODEL_SIZE_MB = 84
        private const val MODEL_FILE_NAME = "pokemon_classifier_int8.onnx"
        private const val MIN_VALID_BYTES = 50L * 1024 * 1024
        private const val DEFAULT_BUFFER_SIZE = 64 * 1024
    }
}
